export const UI = {
  inputField: document.querySelector('.search_res'),
  dataList: document.querySelector('.search-container'),
  resultPage: document.querySelector('.result-page'),
  mainPage: document.querySelector('.main-page'),
  stateName: document.querySelector('.result-statename'),
  cityCountry: document.querySelector('.result-country'),
  city: document.querySelector('.result-city h2'),
  citySummary: document.querySelector('.result-city span'),
  preloader: document.querySelector('.preloader'),
  cityMayor: document.querySelector('.city_mayor h2'),
  externalLink: document.querySelector('.externalInfo'),
  pageImg: document.querySelector('.result-img '),
  safetyScore: document.querySelector('#safety_score'),
  healthScore: document.querySelector('#health_score'),
  eduScore: document.querySelector('#education_score'),
  population: document.querySelector('.population'),
  tempHigh: document.querySelector('.temp-high'),
  tempLow: document.querySelector('.temp-low'),
  currency: document.querySelector('.currency'),
  lang: document.querySelector('.lang'),
  DS: document.querySelector('.download_speed'),
}
